version: '3.7'
services:
  test:
    depends on: bot
    container_name: vinostime-test
  bot:
    container_name: vinostime
    image: nnari/vinostime:latest
    restart: always
    volumes:
      - ./vinostime-logs:/app/logs
    env_file:
      - .env
